hook.new("raw",function(txt)
	txt:gsub("^:"..cnick.." MODE "..cnick.." :%+i",function()
		send("CAP REQ account-notify")
		send("NS IDENTIFY "..file["pass/nspassword.txt"]:match("%S+"))
		async.new(function()
			async.wait(2)
			send("JOIN #oc")
			send("JOIN #ocbots")
			send("JOIN #OpenPrograms")
			send("JOIN #pastamen")
			send("JOIN #ccjam")
			send("JOIN #EpicnessTwo")
		end)
	end)
end)