hook.new("raw",function(txt)
	txt:gsub("^:"..cnick.." MODE "..cnick.." :%+i",function()
		send("CAP REQ account-notify")
		send("NS IDENTIFY "..file["pass/nspassword.txt"]:match("%S+"))
		async.new(function()
			async.wait(1)
			send("JOIN #oc")
			send("JOIN #V")
			send("JOIN #ocgames")
			send("JOIN #OpenPrograms")
			send("JOIN #pastamen")
			send("JOIN #ccjam")
			send("JOIN #EpicnessTwo")
		end)
	end)
end)
if crash then
	async.new(function()
		async.wait(1)
		send("PRIVMSG #V :crash "..(#crash>200 and paste(crash) or crash))
	end)
end
